import { defineCapturePresets } from '@shared/capture/presetHelpers';

const SEEDED_CAMPAIGNS = [
    {
        id: 'camp_demo_yaz_bakimi',
        createdAt: '2026-04-10T09:00:00.000Z',
        icon: '🛢️',
        title: 'Yaz Bakimi Paketi',
        category: 'bakim',
        description: 'Motor yagi, filtre seti ve klima kontrolu birlikte.',
        longDescription: 'Yaz sezonu oncesi genel kontrol, filtre degisimi ve klima verimlilik kontrolu.',
        price: 2690,
        originalPrice: 3290,
        includedItems: [
            { icon: '🛢️', label: 'Motor Yagi Degisimi' },
            { icon: '🌬️', label: 'Hava ve Polen Filtresi' },
            { icon: '❄️', label: 'Klima Kontrolu' },
            { icon: '🔍', label: 'Genel Kontrol' },
        ],
        estimatedDuration: '2-3 saat',
        guarantee: '3 ay / 5.000 km',
        tags: ['Kampanya', 'Populer'],
        startDate: '2026-04-10',
        endDate: '2026-04-30',
    },
    {
        id: 'camp_demo_fren',
        createdAt: '2026-04-06T11:30:00.000Z',
        icon: '🔴',
        title: 'Fren Guvenlik Kontrolu',
        category: 'genel',
        description: 'Balata, disk ve fren hidroligi icin hizli kontrol paketi.',
        longDescription: 'On fren sistemi, disk yuzeyi ve hidrolik seviyesi kontrol edilerek riskler raporlanir.',
        price: 990,
        originalPrice: 1290,
        includedItems: [
            { icon: '🔴', label: 'Balata Kontrolu' },
            { icon: '💿', label: 'Disk Yuzeyi Olcumu' },
            { icon: '💧', label: 'Hidrolik Kontrolu' },
        ],
        estimatedDuration: '45 dk',
        guarantee: '',
        tags: ['Yeni', 'Sinirli Sure'],
        startDate: '2026-04-05',
        endDate: '2026-04-25',
    },
];

export const USTA_CAPTURE_STORAGE_KEYS = [
    'usta_nav_params',
    'usta_pool_jobs',
    'usta_sent_quotes',
    'usta_case_usta_demo_mekanik',
    'usta_case_usta_demo_bakim',
    'usta_case_usta_demo_pool',
    'usta_case_usta_demo_completed_1',
    'usta_case_usta_demo_completed_2',
];

const entries = [
    {
        id: 'usta-overlay-fab',
        group: '00-overlays',
        order: 1,
        title: 'Hizli Islemler',
        screenId: 'screen-usta-home',
        captureMode: 'viewport',
        contextState: {
            currentScreen: 'screen-usta-home',
            activeTab: 'screen-usta-home',
            fabOpen: true,
            availability: 'busy',
        },
    },
    {
        id: 'usta-home',
        group: '01-main-tabs',
        order: 1,
        title: 'Usta Ana Sayfa',
        screenId: 'screen-usta-home',
        contextState: {
            currentScreen: 'screen-usta-home',
            activeTab: 'screen-usta-home',
            availability: 'open',
        },
    },
    {
        id: 'usta-my-jobs',
        group: '01-main-tabs',
        order: 2,
        title: 'Islerim',
        screenId: 'screen-my-jobs',
        contextState: {
            currentScreen: 'screen-my-jobs',
            activeTab: 'screen-my-jobs',
            availability: 'open',
        },
    },
    {
        id: 'usta-pool',
        group: '01-main-tabs',
        order: 3,
        title: 'Is Havuzu',
        screenId: 'screen-pool',
        contextState: {
            currentScreen: 'screen-pool',
            activeTab: 'screen-pool',
            availability: 'open',
        },
    },
    {
        id: 'usta-business-profile',
        group: '01-main-tabs',
        order: 4,
        title: 'Isletme Profili',
        screenId: 'screen-business-profile',
        contextState: {
            currentScreen: 'screen-business-profile',
            activeTab: 'screen-business-profile',
            availability: 'busy',
        },
    },
    {
        id: 'usta-pool-detail',
        group: '02-job-pool',
        order: 1,
        title: 'Havuz Is Detayi',
        screenId: 'screen-pool-detail',
        contextState: {
            currentScreen: 'screen-pool-detail',
            activeTab: 'screen-pool',
            availability: 'open',
        },
        navParams: { poolJobId: 'pool_004' },
    },
    {
        id: 'usta-quote-form',
        group: '02-job-pool',
        order: 2,
        title: 'Teklif Formu',
        screenId: 'screen-quote-form',
        contextState: {
            currentScreen: 'screen-quote-form',
            activeTab: 'screen-pool',
            availability: 'open',
        },
        navParams: { poolJobId: 'pool_004' },
    },
    {
        id: 'usta-job-detail',
        group: '02-job-pool',
        order: 3,
        title: 'Aktif Is Detayi',
        screenId: 'screen-job-detail',
        contextState: {
            currentScreen: 'screen-job-detail',
            activeTab: 'screen-my-jobs',
            availability: 'open',
        },
        navParams: { caseId: 'usta_demo_mekanik' },
    },
    {
        id: 'usta-revenue',
        group: '03-revenue-campaigns',
        order: 1,
        title: 'Gelir Ozeti',
        screenId: 'screen-revenue',
        contextState: {
            currentScreen: 'screen-revenue',
            activeTab: 'screen-usta-home',
            availability: 'open',
        },
    },
    {
        id: 'usta-campaign-create',
        group: '03-revenue-campaigns',
        order: 2,
        title: 'Kampanya Olustur',
        screenId: 'screen-campaign-create',
        contextState: {
            currentScreen: 'screen-campaign-create',
            activeTab: 'screen-usta-home',
            availability: 'busy',
        },
    },
    {
        id: 'usta-my-campaigns',
        group: '03-revenue-campaigns',
        order: 3,
        title: 'Kampanyalarim',
        screenId: 'screen-my-campaigns',
        contextState: {
            currentScreen: 'screen-my-campaigns',
            activeTab: 'screen-usta-home',
            availability: 'busy',
            campaigns: SEEDED_CAMPAIGNS,
        },
    },
];

export const USTA_CAPTURE_PRESETS = defineCapturePresets('usta', entries);
