import { SERVICE_PACKAGES } from '../data/purchaseData';
import { DEMO_QUOTES, DEMO_QUOTE_REQUESTS } from '../data/quoteData';
import { defineCapturePresets } from './presetHelpers';

const CAPTURE_PACKAGE = SERVICE_PACKAGES.find((item) => item.id === 'pkg-yaz-bakim') || SERVICE_PACKAGES[0];

const SEEDED_ORDER = {
    id: 'ORD-LEGACY-001',
    packageId: CAPTURE_PACKAGE.id,
    packageTitle: CAPTURE_PACKAGE.title,
    packageIcon: CAPTURE_PACKAGE.icon,
    price: CAPTURE_PACKAGE.price,
    originalPrice: CAPTURE_PACKAGE.originalPrice,
    provider: CAPTURE_PACKAGE.provider,
    vehicle: { plate: '34 ABC 42', model: 'BMW 3 Serisi · 2019' },
    slot: { day: '2026-04-19', ranges: ['morning'] },
    paymentMethod: 'kredi-karti',
    paymentLabel: 'Kredi Karti',
    status: 'confirmed',
    createdAt: '2026-04-18T08:00:00.000Z',
};

const OWNER_RECENT_SEARCHES = ['bmw zincir', 'yaz bakimi', 'cekici'];

const HASAR_CAPTURE_STATE = {
    hasarType: 'ses',
    isSurulebilir: true,
    cekiciCalled: false,
    description: 'Soguk calistirmada motordan metalik vuruntu geliyor, ilk 30 saniye belirgin.',
    media: ['motor_ses_1.jpg', 'motor_ses_2.mp4', 'obd_ses_notu.aac'],
    dynamicAnswers: {
        ses_tipi: 'Metalik vuruntu',
        ne_zaman: 'Soguk calistirmada',
        siddet: 'Orta',
    },
    servicePref: 'Yakin olsun',
};

const BAKIM_CAPTURE_STATE = {
    maintenanceType: 'periyodik',
    currentKm: '87.400',
    lastMaintenance: 'Mart 2026',
    datePreference: 'Bu hafta',
    selectedItems: {
        motor_yagi: true,
        yag_filtresi: true,
        hava_filtresi: true,
        polen_filtresi: true,
        buji: true,
    },
    itemPartPrefs: {
        motor_yagi: 'Orijinal',
        yag_filtresi: 'Orijinal',
        hava_filtresi: 'Orijinal',
        polen_filtresi: 'Esdeger',
        buji: 'Orijinal',
    },
    note: 'Ayni ziyarette klima kontrolu da yapilabilirse iyi olur.',
};

const KAZA_CAPTURE_STATE = {
    ambulansCagirildi: false,
    cekiciCagirildi: true,
    kazaTipi: 'karsi_tarafli',
    karsiTarafSayisi: 2,
    aciklama: 'Kavsakta sagdan gelen arac on tampondan carpti, arka tarafta da ikinci arac ile temas oldu.',
    fotograflar: {
        genel: ['genel_1.jpg', 'genel_2.jpg'],
        plaka: ['plaka_1.jpg'],
        hasar_detay: ['hasar_detay_1.jpg', 'hasar_detay_2.jpg'],
        cevre: ['cevre_1.jpg'],
        ek: ['ek_1.jpg'],
    },
    tutanakKaynak: 'edevlet',
    tutanakYuklendi: true,
    evraklar: {
        kendi: {
            ehliyet: 'kendi_ehliyet.jpg',
            ruhsat: 'kendi_ruhsat.jpg',
            police: 'kendi_police.jpg',
        },
        karsiTaraf: {
            ehliyet: 'karsi_ehliyet.jpg',
            ruhsat: 'karsi_ruhsat.jpg',
            police: null,
        },
    },
    kaskoBasvuru: true,
    kaskoSirket: 'Anadolu Sigorta',
    sigortaBasvuru: true,
    sigortaSirket: 'Axa Sigorta',
};

const OWNER_CASE_STORAGE_KEYS = [
    'sanayi_case_demo_mekanik',
    'sanayi_case_demo_kaza',
    'sanayi_case_demo_bakim',
    'sanayi_case_demo_pool',
    'sanayi_case_demo_completed_bakim',
    'sanayi_case_demo_completed_hasar',
];

export const OWNER_CAPTURE_STORAGE_KEYS = [
    'sanayi_nav_params',
    'sanayi_quotes',
    'sanayi_quote_requests',
    'sanayi_orders',
    'sanayi_recent_searches',
    'hasar_flow_state',
    'bakim_flow_state',
    'kaza_flow_state',
    'cekici_context',
    ...OWNER_CASE_STORAGE_KEYS,
];

const entries = [
    {
        id: 'owner-overlay-fab',
        group: '00-overlays',
        order: 1,
        title: 'Hizli Aksiyonlar',
        screenId: 'screen-home',
        captureMode: 'viewport',
        contextState: { currentScreen: 'screen-home', activeTab: 'screen-home', fabOpen: true },
    },
    {
        id: 'owner-overlay-vehicle-switcher',
        group: '00-overlays',
        order: 2,
        title: 'Arac Secimi',
        screenId: 'screen-home',
        captureMode: 'viewport',
        contextState: {
            currentScreen: 'screen-home',
            activeTab: 'screen-home',
            vehicleSwitcherOpen: true,
            vehicle: { plate: '34 ABC 42', model: 'BMW 3 Serisi · 2019' },
        },
    },

    {
        id: 'owner-home',
        group: '01-main-tabs',
        order: 1,
        title: 'Ana Sayfa',
        screenId: 'screen-home',
        contextState: { currentScreen: 'screen-home', activeTab: 'screen-home' },
        storageSeed: { sanayi_orders: [SEEDED_ORDER] },
    },
    {
        id: 'owner-kayitlar',
        group: '01-main-tabs',
        order: 2,
        title: 'Kayitlar',
        screenId: 'screen-kayitlar',
        contextState: { currentScreen: 'screen-kayitlar', activeTab: 'screen-kayitlar' },
        storageSeed: {
            sanayi_orders: [SEEDED_ORDER],
            sanayi_quotes: DEMO_QUOTES,
            sanayi_quote_requests: DEMO_QUOTE_REQUESTS,
        },
    },
    {
        id: 'owner-ustalar',
        group: '01-main-tabs',
        order: 3,
        title: 'Ustalar',
        screenId: 'screen-ustalar',
        contextState: { currentScreen: 'screen-ustalar', activeTab: 'screen-ustalar' },
        storageSeed: {
            sanayi_quote_requests: DEMO_QUOTE_REQUESTS,
            sanayi_quotes: DEMO_QUOTES,
        },
    },
    {
        id: 'owner-profil',
        group: '01-main-tabs',
        order: 4,
        title: 'Profil',
        screenId: 'screen-profil',
        contextState: { currentScreen: 'screen-profil', activeTab: 'screen-profil' },
        storageSeed: { sanayi_orders: [SEEDED_ORDER] },
    },

    {
        id: 'owner-swipe',
        group: '02-discovery-match',
        order: 1,
        title: 'Kaydir ve Usta Bul',
        screenId: 'screen-eslestir',
        contextState: { currentScreen: 'screen-eslestir', activeTab: 'screen-home' },
    },
    {
        id: 'owner-usta-profil',
        group: '02-discovery-match',
        order: 2,
        title: 'Usta Profili',
        screenId: 'screen-usta-profil',
        contextState: { currentScreen: 'screen-usta-profil', activeTab: 'screen-ustalar' },
        navParams: { providerId: 'autopro', providerName: 'AutoPro Servis' },
    },

    {
        id: 'owner-cekici',
        group: '03-request-flows',
        order: 1,
        title: 'Cekici Cagir',
        screenId: 'screen-cekici',
        contextState: { currentScreen: 'screen-cekici', activeTab: 'screen-home' },
        storageSeed: {
            cekici_context: { source: 'kaza', arizaType: 'Motor Sesi' },
        },
    },
    {
        id: 'owner-hasar-flow-1',
        group: '03-request-flows',
        order: 2,
        title: 'Ariza Bildir Adim 1',
        screenId: 'screen-hasar-flow',
        contextState: { currentScreen: 'screen-hasar-flow', activeTab: 'screen-home' },
        storageSeed: { hasar_flow_state: HASAR_CAPTURE_STATE },
    },
    {
        id: 'owner-hasar-flow-2',
        group: '03-request-flows',
        order: 3,
        title: 'Ariza Bildir Adim 2',
        screenId: 'screen-hasar-flow-2',
        contextState: { currentScreen: 'screen-hasar-flow-2', activeTab: 'screen-home' },
        storageSeed: { hasar_flow_state: HASAR_CAPTURE_STATE },
    },
    {
        id: 'owner-hasar-flow-3',
        group: '03-request-flows',
        order: 4,
        title: 'Ariza Bildir Adim 3',
        screenId: 'screen-hasar-flow-3',
        contextState: { currentScreen: 'screen-hasar-flow-3', activeTab: 'screen-home' },
        storageSeed: { hasar_flow_state: HASAR_CAPTURE_STATE },
    },
    {
        id: 'owner-hasar-flow-4',
        group: '03-request-flows',
        order: 5,
        title: 'Ariza Bildir Adim 4',
        screenId: 'screen-hasar-flow-4',
        contextState: { currentScreen: 'screen-hasar-flow-4', activeTab: 'screen-home' },
        storageSeed: { hasar_flow_state: HASAR_CAPTURE_STATE },
    },
    {
        id: 'owner-kaza-flow-0',
        group: '03-request-flows',
        order: 6,
        title: 'Kaza Bildir Adim 0',
        screenId: 'screen-kaza-flow-0',
        contextState: { currentScreen: 'screen-kaza-flow-0', activeTab: 'screen-home' },
        storageSeed: { kaza_flow_state: KAZA_CAPTURE_STATE },
    },
    {
        id: 'owner-kaza-flow-1',
        group: '03-request-flows',
        order: 7,
        title: 'Kaza Bildir Adim 1',
        screenId: 'screen-kaza-flow-1',
        contextState: { currentScreen: 'screen-kaza-flow-1', activeTab: 'screen-home' },
        storageSeed: { kaza_flow_state: KAZA_CAPTURE_STATE },
    },
    {
        id: 'owner-kaza-flow-2',
        group: '03-request-flows',
        order: 8,
        title: 'Kaza Bildir Adim 2',
        screenId: 'screen-kaza-flow-2',
        contextState: { currentScreen: 'screen-kaza-flow-2', activeTab: 'screen-home' },
        storageSeed: { kaza_flow_state: KAZA_CAPTURE_STATE },
    },
    {
        id: 'owner-kaza-flow-3',
        group: '03-request-flows',
        order: 9,
        title: 'Kaza Bildir Adim 3',
        screenId: 'screen-kaza-flow-3',
        contextState: { currentScreen: 'screen-kaza-flow-3', activeTab: 'screen-home' },
        storageSeed: { kaza_flow_state: KAZA_CAPTURE_STATE },
    },
    {
        id: 'owner-kaza-flow-4',
        group: '03-request-flows',
        order: 10,
        title: 'Kaza Bildir Adim 4',
        screenId: 'screen-kaza-flow-4',
        contextState: { currentScreen: 'screen-kaza-flow-4', activeTab: 'screen-home' },
        storageSeed: { kaza_flow_state: KAZA_CAPTURE_STATE },
    },
    {
        id: 'owner-kaza-flow-5',
        group: '03-request-flows',
        order: 11,
        title: 'Kaza Bildir Adim 5',
        screenId: 'screen-kaza-flow-5',
        contextState: { currentScreen: 'screen-kaza-flow-5', activeTab: 'screen-home' },
        storageSeed: { kaza_flow_state: KAZA_CAPTURE_STATE },
    },
    {
        id: 'owner-kaza-flow-6',
        group: '03-request-flows',
        order: 12,
        title: 'Kaza Bildir Adim 6',
        screenId: 'screen-kaza-flow-6',
        contextState: { currentScreen: 'screen-kaza-flow-6', activeTab: 'screen-home' },
        storageSeed: { kaza_flow_state: KAZA_CAPTURE_STATE },
    },
    {
        id: 'owner-bakim-flow-1',
        group: '03-request-flows',
        order: 13,
        title: 'Bakim Talebi Adim 1',
        screenId: 'screen-bakim-flow',
        contextState: { currentScreen: 'screen-bakim-flow', activeTab: 'screen-home' },
        storageSeed: { bakim_flow_state: BAKIM_CAPTURE_STATE },
    },
    {
        id: 'owner-bakim-flow-2',
        group: '03-request-flows',
        order: 14,
        title: 'Bakim Talebi Adim 2',
        screenId: 'screen-bakim-flow-2',
        contextState: { currentScreen: 'screen-bakim-flow-2', activeTab: 'screen-home' },
        storageSeed: { bakim_flow_state: BAKIM_CAPTURE_STATE },
    },
    {
        id: 'owner-bakim-flow-3',
        group: '03-request-flows',
        order: 15,
        title: 'Bakim Talebi Adim 3',
        screenId: 'screen-bakim-flow-3',
        contextState: { currentScreen: 'screen-bakim-flow-3', activeTab: 'screen-home' },
        storageSeed: { bakim_flow_state: BAKIM_CAPTURE_STATE },
    },

    {
        id: 'owner-hasar-detail',
        group: '04-case-and-offers',
        order: 1,
        title: 'Hasar Detayi',
        screenId: 'screen-hasar-detail',
        contextState: { currentScreen: 'screen-hasar-detail', activeTab: 'screen-kayitlar' },
    },
    {
        id: 'owner-teklifler',
        group: '04-case-and-offers',
        order: 2,
        title: 'Teklifler',
        screenId: 'screen-teklif',
        contextState: { currentScreen: 'screen-teklif', activeTab: 'screen-kayitlar' },
        storageSeed: { sanayi_quotes: DEMO_QUOTES },
    },
    {
        id: 'owner-servis-takip',
        group: '04-case-and-offers',
        order: 3,
        title: 'Onarim Takibi',
        screenId: 'screen-servis-takip',
        contextState: { currentScreen: 'screen-servis-takip', activeTab: 'screen-kayitlar' },
    },
    {
        id: 'owner-vaka-takibi',
        group: '04-case-and-offers',
        order: 4,
        title: 'Vaka Takibi',
        screenId: 'screen-hasar-takip',
        contextState: { currentScreen: 'screen-hasar-takip', activeTab: 'screen-kayitlar' },
        navParams: { caseId: 'demo_mekanik' },
    },
    {
        id: 'owner-servis-detayi',
        group: '04-case-and-offers',
        order: 5,
        title: 'Servis Detayi',
        screenId: 'screen-servis-detay',
        contextState: { currentScreen: 'screen-servis-detay', activeTab: 'screen-kayitlar' },
    },
    {
        id: 'owner-vaka-havuzu',
        group: '04-case-and-offers',
        order: 6,
        title: 'Vaka Havuzu',
        screenId: 'screen-vaka-havuz',
        contextState: { currentScreen: 'screen-vaka-havuz', activeTab: 'screen-kayitlar' },
        navParams: { caseId: 'demo_pool', quoteId: 'q_001' },
        storageSeed: {
            sanayi_quotes: DEMO_QUOTES,
            sanayi_quote_requests: DEMO_QUOTE_REQUESTS,
        },
    },
    {
        id: 'owner-teklif-detayi',
        group: '04-case-and-offers',
        order: 7,
        title: 'Teklif Detayi',
        screenId: 'screen-teklif-detay',
        contextState: { currentScreen: 'screen-teklif-detay', activeTab: 'screen-kayitlar' },
        navParams: { caseId: 'demo_pool', quoteId: 'q_001', providerId: 'autopro', providerName: 'AutoPro Servis' },
        storageSeed: {
            sanayi_quotes: DEMO_QUOTES,
            sanayi_quote_requests: DEMO_QUOTE_REQUESTS,
        },
    },
    {
        id: 'owner-kesin-kabul',
        group: '04-case-and-offers',
        order: 8,
        title: 'Kesin Kabul',
        screenId: 'screen-kesin-kabul',
        contextState: { currentScreen: 'screen-kesin-kabul', activeTab: 'screen-kayitlar' },
        navParams: { caseId: 'demo_pool', quoteId: 'q_001', providerId: 'autopro', providerName: 'AutoPro Servis' },
        storageSeed: {
            sanayi_quotes: DEMO_QUOTES,
            sanayi_quote_requests: DEMO_QUOTE_REQUESTS,
        },
    },

    {
        id: 'owner-arac-ekle',
        group: '05-vehicles',
        order: 1,
        title: 'Arac Ekle',
        screenId: 'screen-arac-ekle',
        contextState: { currentScreen: 'screen-arac-ekle', activeTab: 'screen-profil' },
    },
    {
        id: 'owner-arac-yonetim',
        group: '05-vehicles',
        order: 2,
        title: 'Arac Yonetimi',
        screenId: 'screen-arac-yonetim',
        contextState: { currentScreen: 'screen-arac-yonetim', activeTab: 'screen-profil' },
        navParams: { vehicleId: 'v1', vehiclePlate: '34 ABC 42', vehicleModel: 'BMW 3 Serisi · 2019' },
    },
    {
        id: 'owner-arac-listesi',
        group: '05-vehicles',
        order: 3,
        title: 'Arac Listesi',
        screenId: 'screen-arac-list',
        contextState: { currentScreen: 'screen-arac-list', activeTab: 'screen-profil' },
    },

    {
        id: 'owner-search',
        group: '06-search-and-purchase',
        order: 1,
        title: 'Arama',
        screenId: 'screen-search',
        contextState: { currentScreen: 'screen-search', activeTab: 'screen-home' },
        navParams: { searchTab: 'tumu' },
        storageSeed: { sanayi_recent_searches: OWNER_RECENT_SEARCHES },
    },
    {
        id: 'owner-package-detail',
        group: '06-search-and-purchase',
        order: 2,
        title: 'Paket Detayi',
        screenId: 'screen-paket-detay',
        contextState: { currentScreen: 'screen-paket-detay', activeTab: 'screen-ustalar' },
        navParams: { packageId: CAPTURE_PACKAGE.id, providerId: CAPTURE_PACKAGE.provider.id, providerName: CAPTURE_PACKAGE.provider.name },
    },
    {
        id: 'owner-checkout',
        group: '06-search-and-purchase',
        order: 3,
        title: 'Satin Alma',
        screenId: 'screen-checkout',
        contextState: { currentScreen: 'screen-checkout', activeTab: 'screen-ustalar' },
        navParams: { packageId: CAPTURE_PACKAGE.id },
    },
    {
        id: 'owner-order-confirm',
        group: '06-search-and-purchase',
        order: 4,
        title: 'Siparis Onayi',
        screenId: 'screen-siparis-onay',
        contextState: { currentScreen: 'screen-siparis-onay', activeTab: 'screen-kayitlar' },
        navParams: { orderId: SEEDED_ORDER.id },
        storageSeed: { sanayi_orders: [SEEDED_ORDER] },
    },

    {
        id: 'owner-bildirimler',
        group: '07-utility',
        order: 1,
        title: 'Bildirimler',
        screenId: 'screen-bildirimler',
        contextState: { currentScreen: 'screen-bildirimler', activeTab: 'screen-home' },
    },
    {
        id: 'owner-destek',
        group: '07-utility',
        order: 2,
        title: 'Yardim Merkezi',
        screenId: 'screen-destek',
        contextState: { currentScreen: 'screen-destek', activeTab: 'screen-profil' },
    },
    {
        id: 'owner-fatura-detayi',
        group: '07-utility',
        order: 3,
        title: 'Fatura Detayi',
        screenId: 'screen-fatura-detay',
        contextState: { currentScreen: 'screen-fatura-detay', activeTab: 'screen-kayitlar' },
    },
];

export const OWNER_CAPTURE_PRESETS = defineCapturePresets('arac-sahibi', entries);
